version: '3'
services:
  database:
    image: postgres:latest
    env_file:
      - .env.prod # change to .env.prod if you want to deploy in prod.
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432' # Expose the PostgreSQL on port 5432

  #uncomment to deploy in prod. (wip)
  app:
    build:
      context: . # Path to your NestJS application code
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - '${PORT}:3000' # Expose your app on port 3000
    depends_on:
      - database
